---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m0s
  chart:
    spec:
      interval: 30m0s
      chart: cilium
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    autoDirectNodeRoutes: true
    bgpControlPlane:
      enabled: true
    bgp:
      enabled: false
      announce:
        loadbalancerIP: true
        podCIDR: false
    bpf:
      hostRouting: true
      lbBypassFIBLookup: true
      masquerade: true
      tproxy: true
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    cluster:
      name: kclt-01
      id: 1
    cni:
      exclusive: false
    containerRuntime:
      integration: containerd
    enableIPv4BIGTCP: true
    # enableIPv6BIGTCP: true
    ipam:
      mode: "kubernetes"
    # one day... (I <3 IPv6) :(
    #ipv6:
    #  enabled: true
    # Matches talconfig clusterPodNets
    ipv4NativeRoutingCIDR: 10.244.0.0/16
    k8sServiceHost: localhost
    k8sServicePort: 7445
    kubeProxyReplacement: true
    loadBalancer:
      algorithm: maglev
      mode: dsr
    operator:
      enabled: true
      rollOutPods: true
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 2
    rollOutCiliumPods: true
    securityContext:
      # False. that is what the list is for.
      privileged: false
      capabilities:
        ciliumAgent:
          # Removal of SYS_MODULE due to security holes.
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        mountCgroup:
          - SYS_ADMIN
          - SYS_CHROOT
          - SYS_PTRACE
        applySysctlOverwrites:
          - SYS_ADMIN
          - SYS_CHROOT
          - SYS_PTRACE
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    tunnel: disabled
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 2
      type: RollingUpdate
