---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m0s
  chart:
    spec:
      interval: 30m0s
      chart: cilium
      version: 1.14.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    autoDirectNodeRoutes: true
    bgpControlPlane:
      enabled: true
    bgp:
      enabled: true
      announce:
        loadbalancerIP: true
        podCIDR: true
    bpf:
      hostRouting: true
      lbBypassFIBLookup: true
      masquerade: true
      tproxy: true
    cluster:
      name: kclt-01
      id: 1
    securityContext:
      # False. that is what the list is for.
      privileged: false
      capabilities:
        ciliumAgent:
          # Removal of SYS_MODULE due to security holes.
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        mountCgroup:
          - SYS_ADMIN
          - SYS_CHROOT
          - SYS_PTRACE
        applySysctlOverwrites:
          - SYS_ADMIN
          - SYS_CHROOT
          - SYS_PTRACE
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    ipam:
      mode: "kubernetes"
    # one day... (I <3 IPv6) :(
    #ipv6:
    #  enabled: true
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
      leaseDuration: 120s
      leaseRenewDeadline: 60s
      leaseRetryPeriod: 1s
    loadBalancer:
      algorithm: maglev
      mode: dsr
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 2
    rollOutCiliumPods: true
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 2
      type: RollingUpdate
