---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./helm-release.yaml
labels:
  - pairs:
      app.kubernetes.io/name: cilium
      app.kubernetes.io/instance: cilium
