---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/clusters/kclt-01/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops 
  dependsOn:
    - name: cluster-global
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-configs
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: global-configs
      - kind: Secret
        name: global-secrets
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: cluster-config
              - kind: Secret
                name: cluster-secrets
              - kind: ConfigMap
                name: global-configs
              - kind: Secret
                name: global-secrets
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: substitution.flux.home.arpa/disabled notin (true)
