---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/clusters/kclt-01/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops 
  dependsOn:
    - name: cluster-global
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-configs
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: global-configs
      - kind: Secret
        name: global-secrets
