---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/clusters/kclt-01/crds
  dependsOn:
    - name: sources 
  prune: false
  sourceRef:
    kind: GitRepository
    name: ops
