---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: global
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/global/
  prune: false
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: ops 
