---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sources 
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/clusters/kclt-01/sources
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops 
