---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud 
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  values:
    image:
      tag: 27.0.2-fpm-alpine
    ingress:
      enabled: true
      className: "nginx"
      path: /
    nginx:
      enabled: true
