apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: auth
spec:
  storageClassName: ${CLUSTER_STORAGE_FILESYSTEM}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
