---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${CLUSTER_NAME}-protonmail-bridge"
  namespace: cert-manager
spec:
  secretName: "${CLUSTER_NAME}-protonmail-bridge"
  issuerRef:
    name: cluster-internal-ca
    kind: ClusterIssuer
  commonName: "127.0.0.1"
  #isCA: true
  dnsNames:
  - "127.0.0.1"
  - ${SECRET__PROTONMAIL_HOST}
