---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: # cluster-apps-exampleApp
  namespace: flux-system
spec:
  dependsOn:
    - name: # cluster-apps-otherExampleApp
  path: # ./k8s/clusters/${CLUSTER_NAME}/apps/exampleNamespace/exampleApp/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
