---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-cluster
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      chart: redis-cluster
      version: 
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  values:
    existingSecret: redis-cluster-config-secrets
    existingSecretPasswordKey: REDIS_SECRET_KEY
    persistence:
      enabled: true
      storageClass: ceph-filesystem
      accessModes:
        - "ReadWriteMany"
      size: 2Gi
