apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-media
  namespace: auth
spec:
  storageClassName: ceph-filesystem
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
