apiVersion: v1
kind: Secret
metadata:
    name: global-secrets
    namespace: flux-system
stringData:
    GLOBALSECRET_TEST: ENC[AES256_GCM,data:tnNM2GY=,iv:iDlpLOTepYoY2Mn+7VzmUPg3cr7aFfzw66/qGQNiR1E=,tag:+CKkwkREH8jlzQqDfUA7xA==,type:str]
    #ENC[AES256_GCM,data:H+c3MtbhAhQ=,iv:2Lr+FHiMXyti7C33W+u0J3qH1Jjdpu8wnjr0m77d5Ws=,tag:n3zOA4wJT9HhYa2DvRssFg==,type:comment]
    GLOBALSECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:elhr8QGYLJKeZA==,iv:VKDgdfeqFKFwnqcrWjOXBZRWayCx5whtHzCP8oek4ns=,tag:j2t4b7ZlnSsNdONClyu7CA==,type:str]
    GLOBALSECRET_TESTING_DOMAIN: ENC[AES256_GCM,data:rujqbKaC+ps8Qdk=,iv:s1BvrCdGLfqYj3a7aSL6tJZoQOmFoyclTad3q6KUATI=,tag:GEljGB/wh6xP/8cphJLhYg==,type:str]
    GLOBALSECRET_SHORT_DOMAIN: ENC[AES256_GCM,data:AEgt9AVXRA==,iv:HA+qT7OQtOwOsETvj21HwKuzkTgzn6WLMg7veQUJvFk=,tag:S8jtgs2B6EjwWwgbCEf4pw==,type:str]
    #ENC[AES256_GCM,data:QxWYvhNduCLWYD/5og==,iv:Vs9hVlTGtRk0u/8hU7YR3Incm6JmgQYOqFsXDcPZBCo=,tag:dedPjb1UHvBXUTnOl0S8EQ==,type:comment]
    GLOBALSECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:KH9lOohdMaMdiglA,iv:0L8cP9eTb5TGV2GSpbS50AqHaSApvdpafNYSp59/xOc=,tag:GNIMskzEeUNLfBZrtNJPjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1spkux7hcrspxgl3xq8x7chykdr2d47q5l0jtucqu4gpkvre2cdfsgf38dz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R1IrSHB4R0F6MThrOTRw
            anlrVE1YZE1iVWswdXdIelRKNExubE5qdUdVCkFDRk8zVWpyUlFNTEdlL0VzazFl
            ZlBtcVRraFIwRVcwb3Jla3gyUEhOY1kKLS0tIGwwODhiMmNMcmtyRWtENXhuYmw0
            WjVQQzBWZ0Y3TlZNZVFyM1hrcW8wbzgKXiTFbwKfI0QtRjBue2FJXzraV+kGye7y
            uEfeNzb8hA1vZ9cAQDMjwLkJbR8e4tQ6qamTvdamEYNdevHPFXMjrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age187teecmpvsa4kcme6apvqege0wqjnwd9whfpkq730m48mf8n93xqjn0jve
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dVNyM2tRQUptL3hLQVcv
            UjN3aGJvUDVoMGZVMmF0aWNzR25Tc3M0aVYwClZDNkt0eGhLdVVkb2ZhcGY4Y2Vj
            OVhtSzcyZmluZDZ2U2lGWW93aGpRS2MKLS0tIFZUcTRNUWVWV05NU2o4S2oyVi9U
            ZW92ajMxTzBLMC9mNitJTU5NWkQ4cDAKtr8xd4/Gr150aBlSViRWEcn604rrZthr
            F+BxkiPS9oMzV3hkB12GdQf/fJ8+n6vl3X07XkJtPSOj26DAen8iTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1urnxat7qu650z3c2ek6gavhqd62d3m07frplnkhnkghxsaapcswqultl68
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1aloyd2J2RS9jWld1OGY0
            Q2Y5UEx5SFhSdDBwK1RDUEtibkI5MWVFV1drClZrNnc3OTVMOXFiREc4bFRZYzlZ
            Z0FHMnIrY0R3YjdYMHdTSG1rN0U0VW8KLS0tIEpRMlgwcTlFWDc0dzZTaTBjaTZJ
            VHJXcjZza3ZVQytTeXFia29JQ1F3cUUK3YQwXrq5dhEVUbtvAH4eivEEafnGuaeQ
            A1l5WMwRGQN3T843xgv4qMwP0mBrMYL5lIFDDMUYr8WBzvQKqTndIw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-19T17:33:16Z"
    mac: ENC[AES256_GCM,data:q5n4yAXdhbO3ICSk1ELJrFVgvr18orW10G2R2HqBHebCIC7oxjS8efUVU0eTajtfqUPFnHvjBm3N9KHjWmgmjrlESu0ehWlq+Wc3HPJtJTaM0JP8i1o3Be2wy6Gg62CVWl3vIC+rEYhuco1nglGbdCt2nP8fb73fzCwIG88P5j0=,iv:Fi3ZXMgzcEB++3tduqDYxh2pba4sTkb69Ge3q/mA3ko=,tag:MbQqazTaDiQdkrJSsOZIGg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
