---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app echo-server
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s 
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 2
        strategy: RollingUpdate
        containers:
          main:
            env:
              PORT: &port 8080
            image: 
              repository: docker.io/jmalloc/echo-server
              tag: 0.3.5
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
                readiness: *probes
                startup:
                  enabled: false
              resources:
                requests:
                  cpu: 5m
                  memory: 10M
                limits:
                  memory: 64M
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    

    ingress:
      main:
        className: nginx
        hosts:
          - host: &host echo.sys.${CLUSTER_NAME}.${GLOBALSECRET__PUBLIC_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
            - *host


    service:
      main:
        ports:
          http:
            port: *port
