---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-configs
data:
  CLUSTER_NAME: "kclt-01"

  TIMEZONE: "America/New_York"
  # cert-manager
  CERT_DEFAULT_CLUSTERISSUER: "letsencrypt-production"
  CERT_STAGING_CLUSTERISSUER: "letsencrypt-staging"
  CERT_PRODUCTION_CLUSTERISSUER: "letsencrypt-production"
  
  # metallb
  METALLB_CIDR: "10.64.3.0/24"
  METALLB_INGRESS_ADDR: "10.64.3.1"
  METALLB_MINECRAFTSURVIVAL_ADDR: "10.64.3.2"
