repos:
  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
    - id: forbid-secrets
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - args:
          - --config-file
          - .github/linters/.yamllint.yaml
        id: yamllint
