---
creation_rules:
    # Attempt first to confirm if file is within a specific cluster. If
    # so encrypt with clusters key. Try both ðŸ“ k8s/ and ðŸ“ talos/
  - path_regex: (k8s|talos)/clusters/kclt-01/.*\.sops\.ya?ml(\.(old|new|tmp|nocommit))?
    encrypted_regex: '((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))'
    # keys: 
    #   age: 
    #     - kclt-01.kube.sys.dotfile.sh
    #   pgp:
    #     - rwx@whits.io (depreciated)
    #     - rwx@whits.io (card)
    age: >-
      age1spkux7hcrspxgl3xq8x7chykdr2d47q5l0jtucqu4gpkvre2cdfsgf38dz 
    pgp: >-
      2CE2F0FA3F3E807815447A06B5B5EEA464CA97AB
      9BB4C5E61E5800ECF5174E6696E67F871ED1AF65
    #
    # If not a cluster, see if the file is in ðŸ“ k8s/ or ðŸ“ talos/
    # if so, default to use global key.
  - path_regex: (k8s|talos)/.*\.sops\.ya?ml(\.(old|new|tmp|nocommit))?
    encrypted_regex: '((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))'
    # keys: 
    #   age: 
    #     - kube.sys.dotfile.sh
    #   pgp:
    #     - rwx@whits.io (depreciated)
    #     - rwx@whits.io (card)
    age: >-
      age187teecmpvsa4kcme6apvqege0wqjnwd9whfpkq730m48mf8n93xqjn0jve
    pgp: >-
      2CE2F0FA3F3E807815447A06B5B5EEA464CA97AB
      9BB4C5E61E5800ECF5174E6696E67F871ED1AF65
    # If nothing's taking, encrypt solely with Whit personal key.
  - path_regex: .*\.sops\.ya?ml(\.(old|new|tmp|nocommit))?
    # keys:
    #   pgp:
    #     - rwx@whits.io (depreciated)
    #     - rwx@whits.io (card)
    pgp: >-
      2CE2F0FA3F3E807815447A06B5B5EEA464CA97AB
      9BB4C5E61E5800ECF5174E6696E67F871ED1AF65
