---
creation_rules:
    # Cluster-specific secrets under kubernetes/clusters/kclt-01/
  - path_regex: kubernetes/clusters/kclt-01/.*\.sops\.ya?ml(\.(old|new|tmp|nocommit))?
    encrypted_regex: '((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))'
    # age: kclt-01 cluster key
    age: >-
      age1spkux7hcrspxgl3xq8x7chykdr2d47q5l0jtucqu4gpkvre2cdfsgf38dz
    # App-level secrets under kubernetes/ (non-cluster)
  - path_regex: kubernetes/.*\.sops\.ya?ml(\.(old|new|tmp|nocommit))?
    encrypted_regex: '((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))'
    # age: global key
    age: >-
      age187teecmpvsa4kcme6apvqege0wqjnwd9whfpkq730m48mf8n93xqjn0jve
    # Talos cluster secrets
  - path_regex: talos/.*\.sops\.ya?ml(\.(old|new|tmp|nocommit))?
    encrypted_regex: '((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))'
    # age: global key
    age: >-
      age187teecmpvsa4kcme6apvqege0wqjnwd9whfpkq730m48mf8n93xqjn0jve
    # Fallback: encrypt solely with personal PGP keys.
  - path_regex: .*\.sops\.ya?ml(\.(old|new|tmp|nocommit))?
    # keys:
    #   pgp:
    #     - rwx@whits.io (depreciated)
    #     - rwx@whits.io (card)
    pgp: >-
      2CE2F0FA3F3E807815447A06B5B5EEA464CA97AB,
      9BB4C5E61E5800ECF5174E6696E67F871ED1AF65
