---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kyverno
  namespace: flux-system
spec:
  path: ${CLUSTER_PATH}/apps/kyverno/kverno/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true 
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kyverno-policies
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-kyverno
  path: ${CLUSTER_PATH}/apps/kyverno/kverno/policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
