---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: global-git-ops
  namespace: flux-system
spec:
  interval: 5m0s
  ref:
    branch: main
  url: https://github.com/dotfilesh/ops.git
  ignore: |
    # exclude all
    /*
    # include gitops dirs
    !/k8s
