---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-alertmanager
  namespace: flux-system
spec:
  path: ${CLUSTER_PATH}/apps/monitoring/alertmanager/app
  prune: true
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
