---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kubelet-csr-approver
      version: 1.0.5
      sourceRef:
        kind: HelmRepository
        name: postfinance
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # yeah I know this is ugly.
    # consequence of my sin (wanting cool names)
    providerRegex: |
      ^(junks|woglinde|wellgunde|flosshilde|formula|urban|verus|lailah|mastema|amdusias)$
    providerRexgex: 
    providerIpPrefixes: 10.64.6.0/20
    bypassDnsResolution: true

