---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app goldilocks
  namespace: metrics
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 6.7.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      resources:
        requests:
          cpu: 10m
          memory: 500M
        limits:
          memory: 1G
    dashboard:
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "goldilocks.${CLUSTER_NAME}.sys.${GLOBALSECRET__PUBLIC_DOMAIN}"
            paths:
              - path: /
                type: Prefix
        tls:
          - hosts:
              - *host
            secretName: goldilocks.${CLUSTER_NAME}.sys.${GLOBALSECRET__PUBLIC_DOMAIN}
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 100M
