---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nextcloud
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-nextcloud-cnpg-cluster
    #- name: cluster-apps-authentik-redis-cluster
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-rook-ceph-cluster
  path: ./k8s/clusters/${CLUSTER_NAME}/apps/default/nextcloud/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-nextcloud-cnpg-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-rook-ceph-cluster
  path: ./k8s/clusters/${CLUSTER_NAME}/apps/default/nextcloud/cnpg-cluster/
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: cluster-apps-nextcloud-redis-cluster
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: cluster-apps-rook-ceph-cluster
#    - name: cluster-apps-cert-manager-issuers
#  path: ./k8s/clusters/${CLUSTER_NAME}/apps/default/nextcloud/redis-cluster
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: ops
#  wait: true
#  interval: 30m
#  retryInterval: 1m
#  timeout: 5m
