---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-operator
  namespace: flux-system
spec:
  path: ${CLUSTER_PATH}/apps/rook-ceph/rook-ceph/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph-operator
  path: ${CLUSTER_PATH}/apps/rook-ceph/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-certificates
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph-operator
    - name: cluster-apps-rook-ceph-cluster
    - name: cluster-apps-cert-manager
    - name: cluster-apps-cert-manager-issuers
  path: ${CLUSTER_PATH}/apps/rook-ceph/rook-ceph/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-rook-direct-mount
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph-operator
    - name: cluster-apps-rook-ceph-cluster
  path: ${CLUSTER_PATH}/apps/rook-ceph/rook-ceph/rook-direct-mount
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
