---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-node-exporter
      version: 4.24.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: node-exporter
    image:
      registry: quay.io
      repository: prometheus/node-exporter


    prometheus:
      monitor:
        enabled: true
        jobLabel: app.kubernetes.io/instance

          
    hostNetwork: false
