---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m0s
  chart:
    spec:
      interval: 30m0s
      chart: cilium
      version: 1.13.1
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    cluster:
      name: kclt-01
    # required for Cilium >=1.12 due to it liking to poke at the
    # kernel without asking.
    securityContext:
      privileged: true
    ipam:
      mode: "kubernetes"
    # one day... (I <3 IPv6) :(
    #ipv6:
    #  enabled: true
    updateStrategy:
      rollingUpdate:
        maxUnavailable: 2
      type: RollingUpdate
    podDisruptionBudget:
      enabled: true
      maxUnavailable: 2
