---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ops 
  namespace: flux-system
spec:
  secretRef:
    name: github-token
  interval: 5m0s
  ref:
    branch: main
  url: ssh://git@github.com/dotfilesh/ops.git
  ignore: |
    # exclude all
    /*
    # include k8s gitops dirs
    !/k8s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kclt-01.ops
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s/clusters/kclt-01/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: ops
