---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 5m
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: v1.13.8
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    crds:
      enabled: true
    csi:
      kubeletDirPath: /var/lib/kubelet
      enableCSIHostNetwork: true
      enableGrpcMetrics: true
      pluginTolerations:
        - effect: "NoExecute"
          operator: "Exists"
        - effect: "NoSchedule"
          operator: "Exists"
      csiAddons:
        enabled: true
      enableRdbDriver: true
      enableCephfsDriver: true
      serviceMonitor:
        enabled: true
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 200M
      limits:
        memory: 512M
