---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ocis
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: ocis
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: owncloud
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    
