---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-kubelet-csr-approver
  namespace: flux-system
spec:
  path: ./k8s/clusters/${CLUSTER_NAME}/apps/kube-system/kubelet-csr-approver/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
