---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.2.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: storage
              accessMode: ReadWriteOnce
              size: 50Mi
              storageClass: ${CLUSTER_STORAGE_BLOCK_HDD} 
              globalMounts:
                - path: /alertmanager
      
        containers:
          main:
            image:
              repository: quay.io/prometheus/alertmanager
              tag: v0.26.0
            ports:
              - name: http
                containerPort: 9093
            resources:
              requests:
                cpu: 11m
                memory: 50M
              limits:
                memory: 100M
    
    
    service:
      main:
        ports:
          http:
            port: 9093


    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: &host alertmanager.${CLUSTER_NAME}.api.${GLOBALSECRET__PUBLIC_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
            - *host
