---
# See the cnpg-cluster folder for an explanation
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: authentik-cnpg-keypatch
  namespace: auth
spec:
  interval: 30m
  path: "./k8s/clusters/kclt-01/apps/auth/authentik/cnpg-cluster"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-cluster
    namespace: flux-system
  #decryption:
  #  provider: sops
  #  secretRef:
  #    name: sops-age
  dependsOn:
    - name: core
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        # The ConfigMap will not be present at first.
        optional: true
        name: authentik-cnpg-backup
