---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: lb-pool
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cilium
    app.kubernetes.io/instance: cilium
spec:
  cidrs:
    - cidr: ${CILIUM_LB_CIDR}
