---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2023.10.4
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  values:
    authentik:
      email:
        from: ${SECRET__PROTONMAIL_FROM}
        host: ${SECRET__PRPTONMAIL_STATICIP}
        port: ${SECRET__PROTONMAIL_PORT}
        username: ${SECRET__PROTONMAIL_USER}
        password: ${SECRET__PROTONMAIL_PASSWORD}
        use_tls: true
      error_reporting:
        enabled: true
      postgresql:
        # Uses a dedicated cnpg cluster.
        host: "authentik-cnpg-rw"
        name: "authentik"
    postgresql:
      # disable the built-in PostgreSQL chart.
      enabled: false
    prometheus:
      rules:
        create: true
      serviceMonitor:
        create: true
    ingress:
      ingressClassName: "nginx"
      enabled: true
      hosts:
        - host: &host auth.${GLOBALSECRET__PUBLIC_DOMAIN}
          paths:
            - path: "/"
              pathType: Prefix
    redis:
      # enable the built-in redis chart.
      # TODO: Move away from redis built-in subchart.
      enabled: true
    replicas: 3
    securityContext:
      fsGroup: 1000
    volumes:
      - name: media
        persistentVolumeClaim:
          claimName: authentik-media
      - name: cluster-internal-ca
        configMap:
          name: cluster-internal-ca
      - name: protonmail-bridge-cert
        configMap:
          name: protonmail-bridge-cert
    volumeMounts:
      - mountPath: /media
        name: media
      - mountPath: /etc/ssl/certs/ca-certificates.crt
        name: cluster-internal-ca
        optional: true
        readOnly: true
        subPath: cluster-internal-ca.pem
      - mountPath: /etc/ssl/certs/protonmail-bridge-cert.pem
        name: protonmail-bridge-cert
        optional: true
        subPath: protonmail-bridge-cert.pem
        readOnly: true
    worker:
      replicas: 3
      securityContext:
        fsGroup: 1000
  valuesFrom:
    - targetPath: authentik.secret_key
      kind: Secret
      name: authentik-config-secrets
      valuesKey: AUTHENTIK_SECRET_KEY
    - targetPath: authentik.postgresql.password
      kind: Secret
      # the authentik user generated by CNPG initdb
      name: authentik-cnpg-user-authentik
      valuesKey: password
    - targetPath: authentik.postgresql.user
      kind: Secret
      # the authentik user generated by CNPG initdb
      name: authentik-cnpg-user-authentik
      valuesKey: username
