---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        # Setting this expands which group ID can be assigned to
        # a process. 44 and 109 are related to hardware encoding,
        # which at this time is not available.
        supplementalGroups:
          - 44
          #- 105
          #- 109


    controllers:
      jellyfin:
        type: statefulset
        containers:
          app:
            env:
              DOTNET_SYSTEM_IO_DISABLEFILELOCKING: "true"
              JELLYFIN_FFmpeg__probesize: 50000000
              JELLYFIN_FFmpeg__analyzeduration: 50000000
              JELLYFIN_PublishedServerUrl: &host watch.${SECRET__TERTIARY_DOMAIN}
              TZ: ${TIMEZONE}
            image:
              repository: ghcr.io/onedr0p/jellyfin
              tag: 10.8.11@sha256:926e2a9f6677a0c7b12feba29f36c954154869318d6a52df72f72ff9c74cf494
            probes:
              liveness: &probes
                # Jellyfin is PAINFULLY slow.
                enabled: false
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 120
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 2048Mi
        pod:
          #nodeSelector:
            #gpulabel: "true"
        # jellyfin only allows for one container.
        replicas: 1
        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 32Gi
              storageClass: ${CLUSTER_STORAGE_BLOCK_SSD}
              mountPath: /config


    ingress:
      jellyfin:
        enabled: true
        className: "nginx"
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: jellyfin
                  port: http
        tls:
          - hosts:
              - *host
            secretName: *host


    persistence:
      media:
        globalMounts:
          - path: /media
        existingClaim: watch-media
        retain: true
      
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache


    service:
      jellyfin:
        controller: jellyfin
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${CILIUM_LB_JELLYFIN_ADDR}
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: *port 
