---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  values:
    image:
      repository: jellyfin/jellyfin
      pullPolicy: IfNotPresent
      tag: 10.8.11
    controller:
      enabled: true
      type: statefulset
      # jellyfin only allows for one container.
      replicas: 1
    env:
      TZ: ${TIMEZONE}
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host watch.${SECRET__TERTIARY_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: *host
    persistence:
      media:
        enabled: true
        type: pvc
        mountPath: /media
        existingClaim: watch-media
        retain: true
      data:
        enabled: true
        type: pvc
        mountPath: /data
        storageClass: ${CLUSTER_STORAGE_BLOCK_SSD}
        accessMode: ReadWriteOnce
        size: 16Gi
        retain: false
      config:
        enabled: true
        type: pvc
        mountPath: /config
        storageClass: ceph-block-ssd
        accessMode: ReadWriteOnce
        size: 32Gi
        retain: false
      cache:
        enabled: true
        type: emptyDir
        mountPath: /cache
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      # Setting this expands which group ID can be assigned to
      # a process. 44 and 109 are related to hardware encoding,
      # which at this time is not available.
      supplementalGroups:
        - 44
       #- 109
    probes:
      liveness:
        # Jellyfin is PAINFULLY slow.
        enabled: false
        custom: true
        spec:
          httpGet:
            path: /health
            port: &port 8096
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
      readiness:
        enabled: false
        custom: true
        spec:
          httpGet:
            path: /health
            port: *port
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
    service:
      main:
        ports:
          http:
            port: *port 
    resources:
      requests:
        cpu: 10m
        memory: 512Mi
      limits:
        memory: 2048Mi
