---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trust-manger
  namespace: &namespace cert-manager
spec:
  interval: 30m
  chart:
    spec:
      chart: trust-manager
      version: &version v0.6.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    app:
      trust:
        namespace: *namespace
    crds:
      enabled: true
    defaultPackage:
      enabled: false
    image:
      tag: *version
