---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: # exampleServiceThing
  namespace: # Should match dir name of "../../../"
spec:
  interval: 30m
  chart:
    spec:
      chart: # exampleChart
      version: # Version
      sourceRef:
        kind: HelmRepository
        name: # exampleChartRepo
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    key: value
