---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-trust-manager
  namespace: flux-system
spec:
  path: ${CLUSTER_PATH}/apps/cert-manager/trust-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-trust-manager-bundles
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
    - name: cluster-apps-cert-manager-certs
    - name: cluster-apps-trust-manager
  path: ${CLUSTER_PATH}/apps/cert-manager/trust-manager/bundles
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
