---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vpa
  namespace: metrics
spec:
  interval: 30m
  chart:
    spec:
      chart: *app
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    recommender:
      enabled: true
      extraArgs:
        storage: prometheus
        prometheus-address: |-
          http://thanos-query.metrics.svc.cluster.local:9090
    updater:
      enabled: false
    admissionController:
      enabled: false
