---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-cnpg
  namespace: default
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: immich-cnpg
