---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - backup.yaml
  - cluster.yaml
  - helm-release.yaml
    #- objectstoreuser.yaml
  - secret.sops.yaml
