---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: cloudnative-pg
  namespace: rook-ceph
spec:
  store: ceph-bucket
  displayName: cloudnative-pg
  quotas:
    maxBuckets: 1
    maxSize: 50G
  capabilities:
    user: "*"
    bucket: "*"
    usage: "*"
    metadata: "*"
    zone: "read"
