---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: cloudnative-pg
  namespace: rook-ceph
  labels:
    # this is necessary for a kyverno policy which will copy the
    # secret from rook-ceph to database
    sync_secret_to_namespace: database
spec:
  store: ceph-bucket
  displayName: cloudnative-pg
  quotas:
    maxBuckets: 1
    maxSize: 50G
  capabilities:
    user: "*"
    bucket: "*"
    usage: "*"
    metadata: "*"
    zone: "read"
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: cloudnative-pg-backup
  namespace: rook-ceph
spec:
  generateBucketName: cloudnative-pg-backup
  storageClassName: ceph-bucket
  additionalConfig:
    maxSize: 50G
