---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-cnpg
  namespace: auth
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: authentik-cnpg
