---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-cnpg
  namespace: auth
spec:
  instances: 3
  imageName: ghcr.io/cloudnativepg/postgresql:15.4-5
  description: "authentik CNPG database"
  primaryUpdateStrategy: unsupervised
  storage:
    size: 2Gi
    storageClass: ${CLUSTER_STORAGE_BUCKET}
  superuserSecret:
    name: authentik-cnpg-user-superuser
    # This is needed to initialize the database, however it means
    # recovery is a process which requires this value to be CHANGED 
    # from `initdb` to `recovery`. It has to be initdb the first time
    # and should be recovery all subsequent times. There is no way to 
    # intelligently do this.
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-cnpg-user-authentik
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
          # TODO: Investigate viability of encrypted backups.
        #encryption: AES256
        maxParallel: 8
      # endpointURL: &endpointUrl https://s3.${CLUSTER_NAME}.api.${GLOBALSECRET__PUBLIC_DOMAIN}/
        # Using the internal service name WILL work, but is kinda ugly
        # versus using the public URL. Kept for posterity.
      endpointURL: &endpointUrl http://rook-ceph-rgw-ceph-bucket.rook-ceph.svc/
        # Should mirror EXACTLY the value in ./objectbucketclaim.yaml
      destinationPath: &destinationPath s3://authentik-cnpg-backup-12e782ad-0ccc-4113-bc3b-64be8713a7d7/
      s3Credentials:
        accessKeyId:
          name: authentik-cnpg-backup 
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: authentik-cnpg-backup 
          key: AWS_SECRET_ACCESS_KEY
  externalClusters:
    - name: authentik-cnpg-backup
      barmanObjectStore:
        wal:
          compression: bzip2
          maxParallel: 8
        endpointURL: *endpointUrl
        destinationPath: *destinationPath
        s3Credentials:
          accessKeyId:
            name: authentik-cnpg-backup 
            key: AWS_ACCESS_KEY_ID 
          secretAccessKey:
            name: authentik-cnpg-backup 
            key: AWS_SECRET_ACCESS_KEY
