---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: source-metallb
  namespace: flux-system
spec:
  interval: 6h
  url: https://github.com/metallb/metallb.git
  ref:
    tag: v0.13.7
  ignore: |
    # exclude all
    /*
    # include CRDs
    !/charts/metallb/charts/crds/templates
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds-metallb
  namespace: flux-system
spec:
  interval: 6h
  prune: false
  timeout: 5m0s
  wait: true
  sourceRef:
    kind: GitRepository
    name: source-metallb
    namespace: flux-system
