apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "s3-${CLUSTER_NAME}-api-${GLOBALSECRET__PUBLIC_DOMAIN/./-}"
  namespace: rook-ceph
spec:
  secretName: "s3.${CLUSTER_NAME}.api.${GLOBALSECRET__PUBLIC_DOMAIN}"
  issuerRef:
    name: "${CERT_DEFAULT_CLUSTERISSUER}"
    kind: ClusterIssuer
  commonName: "s3.${CLUSTER_NAME}.api.${GLOBALSECRET__PUBLIC_DOMAIN}"
  dnsNames:
  - "s3.${CLUSTER_NAME}.api.${GLOBALSECRET__PUBLIC_DOMAIN}"
