---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../init/source-helm-cilium/
  - cilium-installation.yaml
  - cilium
  - ../../../../init/source-git-flux/
  - flux.yaml
  - ops.yaml
