---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: thanos-ceph-bucket
  namespace: monitoring
spec:
  generateBucketName: thanos-bucket
  storageClassName: ceph-bucket
  additionalConfig:
    maxSize: 50G
