---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: source-kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 6h
  url: https://github.com/prometheus-community/helm-charts.git
  ref:
    # renovate: registryUrl=https://prometheus-community.github.io/helm-charts chart=kube-prometheus-stack
    tag: kube-prometheus-stack-47.0.0
  ignore: |
    # exclude all
    /*
    # include CRDs
    !/charts/kube-prometheus-stack/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds-kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 6h
  prune: false
  timeout: 5m0s
  wait: true
  sourceRef:
    kind: GitRepository
    name: source-kube-prometheus-stack
    namespace: flux-system
