apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "thanos-${CLUSTER_NAME}-api-${GLOBALSECRET_PUBLIC_DOMAIN/./-}"
  namespace: metrics
spec:
  secretName: "thanos.${CLUSTER_NAME}.api.${GLOBALSECRET_PUBLIC_DOMAIN}"
  issuerRef:
    name: "${CERT_DEFAULT_CLUSTERISSUER}"
    kind: ClusterIssuer
  commonName: "thanos.${CLUSTER_NAME}.api.${GLOBALSECRET_PUBLIC_DOMAIN}"
  dnsNames:
  - "*.thanos.${CLUSTER_NAME}.api.${GLOBALSECRET_PUBLIC_DOMAIN}"

