---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: metrics
spec:
  interval: 30m
  chart:
    spec:
      chart: thanos
      version: 11.5.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: kube-prometheus-stack
      namespace: metrics
  values:
    # NOTE: do not be illiterate. this does *not* say 
    # `existingObjectstoreSecret`. This says `existingObjstoreSecret`, 
    # which is what the helm chart expects.
    # NOTE: This secret is expected to have a key "objstore.yml" which
    # is structured as follows:
    # config:
    #   access_key: <string>
    #   bucket: <string>
    #   endpoint: <string>
    #   insecure: <boolean>
    #   region: <string>
    #   secret_key: <string>
    # type: s3
    existingObjstoreSecret: "thanos-objstore-secret"
    query:
      enabled: true
      replicaCount: 3
      replicaLabel:
        - "__replica__"
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: metrics
      ingress:
        enabled: true
        # NOTE: why isn't this using the standard hots[] setup?
        hostname: &host "query.thanos.${CLUSTER_NAME}.api.${GLOBALSECRET_PUBLIC_DOMAIN}"
        ingressClassName: "nginx"
        tls: true
        extraTls:
          - hosts:
            - *host
            secretName: &thanosWebSecret thanos.${CLUSTER_NAME}.api.${GLOBALSECRET_PUBLIC_DOMAIN}
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: true
      replicaCount: 3
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 1
      podAntiAffinityPreset: hard
      ingress:
        enabled: true
        hostname: &host "bucketweb.thanos.${CLUSTER_NAME}.api.${GLOBALSECRET_PUBLIC_DOMAIN}"
        ingressClassName: "nginx"
        tls: true
        extraTls:
          - hosts:
            - *host
            secretName: *thanosWebSecret
    compactor:
      enabled: true
      extraFlags:
        - "--compact.concurrency"
        - "4"
      retentionResolutionRaw: 14d
      retentionResolution5m: 14d
      retentionResolution1h: 14d
      ingress:
        enabled: true
        hostname: &host "compactor.thanos.${CLUSTER_NAME}.api.${GLOBALSECRET_PUBLIC_DOMAIN}"
        ingressClassName: "nginx"
        tls: true
        extraTls:
          - hosts:
            - *host
            secretName: *thanosWebSecret
      persistence:
        enabled: true
        storageClass: "ceph-block"
        size: 50Gi
    storegateway:
      enabled: true
      replicaCount: 3
      podAntiAffinityPreset: hard
      ingress:
        enabled: true
        hostname: &host "storagegateway.thanos.${CLUSTER_NAME}.api.${GLOBALSECRET_PUBLIC_DOMAIN}"
        ingressClassName: "nginx"
        tls: true
        extraTls:
          - hosts:
            - *host
            secretName: *thanosWebSecret
      persistence:
        enabled: true
        storageClass: "ceph-block"
        size: 20Gi
    ruler:
      enabled: true
      replicaCount: 3
      podAntiAffinityPreset: hard
      dnsDiscovery:
        enabled: true
      alertmanagers:
        - http://kube-prometheus-stack-alertmanager.metrics:9093
      clusterName: ${CLUSTER_NAME}
      extraFlags:
        - "--web.prefix-header=X-Forwarded-Prefix"
      config: |-
        groups:
          - name: "PrometheusWatcher"
            rules:
              - alert: "PrometheusDown"
                expr: absent(up{job="kube-prometheus-stack-prometheus"})
      ingress:
        enabled: true
        hostname: &host "ruler.thanos.${CLUSTER_NAME}.api.${GLOBALSECRET_PUBLIC_DOMAIN}"
        ingressClassName: "nginx"
        tls: true
        extraTls:
          - hosts:
            - *host
            secretName: *thanosWebSecret
      persistence:
        enabled: true
        storageClass: "ceph-block"
        size: 20Gi
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
