clusterName: kclt-01
talosVersion: v1.5.0
kubernetesVersion: v1.28.0
endpoint: https://${clusterEndpointIP}:6443
domain: cluster.local
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: none
nodes:
  - hostname: junks # Temporary.
    ipAddress: 10.64.8.254
    controlPlane: true
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
    namservers:
      - 1.1.1.1
      - 9.9.9.9
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        dhcp: true
        mtu: 1500
        vip:
          ip: ${clusterEndpointIP}
  - hostname: woglinde
    ipAddress: 10.64.8.1
    controlPlane: true
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
      size: <= 150GB
    namservers:
      - 1.1.1.1
      - 9.9.9.9
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        dhcp: true
        mtu: 1500
        vip:
          ip: ${clusterEndpointIP}
  - hostname: wellgunde
    ipAddress: 10.64.8.2
    controlPlane: true
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
      size: <= 150GB
    namservers:
      - 1.1.1.1
      - 9.9.9.9
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        dhcp: true
        mtu: 1500
        vip:
          ip: ${clusterEndpointIP}
  - hostname: flosshilde
    ipAddress: 10.64.8.3
    controlPlane: true
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
      size: <= 150GB
    namservers:
      - 1.1.1.1
      - 9.9.9.9
      - 8.8.8.8
    networkInterfaces:
      - interface: eth0
        dhcp: true
        mtu: 1500
        vip:
          ip: ${clusterEndpointIP}
  - hostname: formula
    ipAddress: 10.64.8.9
    controlPlane: false
    installDiskSelector:
      type: nvme
      size: <= 150GB
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
  - hostname: urban
    ipAddress: 10.64.8.10
    controlPlane: false
    installDiskSelector:
      type: nvme
      size: <= 150GB
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
  - hostname: lailah
    ipAddress: 10.64.8.11
    controlPlane: false
    installDiskSelector:
      type: nvme
      size: <= 150GB
    networkInterfaces:
      - interface: eth0
        dhcp: true
        mtu: 1500
  - hostname: verus
    ipAddress: 10.64.8.12
    controlPlane: false
    installDiskSelector:
      type: nvme
      size: <= 150GB
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
  - hostname: mastema
    ipAddress: 10.64.8.13
    controlPlane: false
    installDiskSelector:
      type: nvme
      size: <= 150GB
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
  - hostname: amdusias
    ipAddress: 10.64.8.14
    controlPlane: false
    installDiskSelector:
      type: nvme
      size: <= 150GB
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
controlPlane:
  inlinePatch:
    cluster:
      aescbcEncryptionSecret: ${aescbcEncryptionKey}
      apiServer:
        disablePodSecurityPolicy: true
        admissionControl: []
        certSANs:
          - ${clusterEndpointIP}
          - ${kubeDomainName}
          - ${secretIPv4}
    machine:
      certSANs:
        - ${clusterEndpointIP}
        - ${kubeDomainName}
        - ${secretIPv4}
      files:
        - content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
          path: /etc/cri/conf.d/20-customization.part
          op: create
      network:
        extraHostEntries:
          - aliases:
              - ${kubeDomainName}
            ip: ${clusterEndpointIP}
  patches:
    - | -
      - op: add
        path: /machine/features
        value:
          kubePrism:
            enabled: true
worker:
  inlinePatch:
    cluster:
      aescbcEncryptionSecret: ${aescbcEncryptionKey}
    machine:
      certSANs:
        - ${clusterEndpointIP}
        - ${kubeDomainName}
        - ${secretIPv4}
      files:
        - content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
          path: /etc/cri/conf.d/20-customization.part
          op: create
      network:
        extraHostEntries:
          - aliases:
              - ${kubeDomainName}
            ip: ${clusterEndpointIP}
  patches:
    - | -
      - op: add
        path: /machine/features
        value:
          kubePrism:
            enabled: true
