clusterName: &clusterName kclt-01
talosVersion: v1.5.4
kubernetesVersion: v1.28.3
endpoint: https://${clusterEndpointIP}:6443
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
additionalApiServerCertSans:
  - ${clusterEndpointIP}
  - ${secretKubeDomainName}
  - ${secretIPv4}
additionalMachineCertSans:
  - ${clusterEndpointIP}
  - ${secretKubeDomainName}
  - ${secretIPv4}
cniConfig:
  name: none
nodes:
  - hostname: junks # Temporary.
    ipAddress: 10.64.6.8
    controlPlane: true
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
    namservers:
      - 1.1.1.1
      - 9.9.9.9
      - 8.8.8.8
    networkInterfaces:
      - interface: bond0
        bond:
          mode: 802.3ad
          deviceSelectors:
            - hardwareAddr: '00:e0:4c:01:49:94'
        dhcp: false
        mtu: 9000
        addresses:
          - 10.64.6.8/20
        routes:
          - network: 0.0.0.0/0
            gateway: 10.64.0.1
        vip:
          ip: ${clusterEndpointIP}
    nodeLabels: &controllerLabels
      node-role.kubernetes.io/control-plane: "control-plane"
      topology.kubernetes.io/region: "us-east"
      topology.kubernetes.io/zone: *clusterName
          
  - hostname: woglinde
    ipAddress: 10.64.6.1
    controlPlane: true
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
      size: <= 150GB
    namservers:
      - 1.1.1.1
      - 9.9.9.9
      - 8.8.8.8
    networkInterfaces:
      - interface: eno1
        dhcp: false
        mtu: 9000
        addresses:
          - 10.64.6.1/20
        routes:
          - network: 0.0.0.0/0
            gateway: 10.64.0.1
        vip:
          ip: ${clusterEndpointIP}
    nodeLabels: *controllerLabels
  
  - hostname: wellgunde
    ipAddress: 10.64.6.2
    controlPlane: true
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
      size: <= 150GB
    namservers:
      - 1.1.1.1
      - 9.9.9.9
      - 8.8.8.8
    networkInterfaces:
      - interface: eno1
        dhcp: false
        mtu: 9000
        addresses:
          - 10.64.6.2/20
        routes:
          - network: 0.0.0.0/0
            gateway: 10.64.0.1
        vip:
          ip: ${clusterEndpointIP}
    nodeLabels: *controllerLabels
  
  - hostname: flosshilde
    ipAddress: 10.64.6.3
    controlPlane: true
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
      size: <= 150GB
    namservers:
      - 1.1.1.1
      - 9.9.9.9
      - 8.8.8.8
    networkInterfaces:
      - interface: eno1
        dhcp: false
        mtu: 9000
        addresses:
          - 10.64.6.3/20
        routes:
          - network: 0.0.0.0/0
            gateway: 10.64.0.1
        vip:
          ip: ${clusterEndpointIP}
    nodeLabels: *controllerLabels
  
  - hostname: formula
    ipAddress: 10.64.6.9
    controlPlane: false
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
      size: <= 150GB
    networkInterfaces:
      - interface: eno1
        addresses:
          - 10.64.6.9/20
        routes:
          - network: 0.0.0.0/0
            gateway: 10.64.0.1
        mtu: 9000
        dhcp: false
    nodeLabels: &workerLabels
      node-role.kubernetes.io/worker: "worker"
      topology.kubernetes.io/region: "us-east"
      topology.kubernetes.io/zone: *clusterName
  
  - hostname: urban
    ipAddress: 10.64.6.10
    controlPlane: false
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
      size: <= 150GB
    networkInterfaces:
      - interface: eno1
        addresses:
          - 10.64.6.10/20
        routes:
          - network: 0.0.0.0/0
            gateway: 10.64.0.1
        mtu: 9000
        dhcp: false
    nodeLabels: *workerLabels
  
  - hostname: lailah
    ipAddress: 10.64.6.11
    controlPlane: false
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
      size: <= 150GB
    networkInterfaces:
      - interface: eno1
        addresses:
          - 10.64.6.11/20
        routes:
          - network: 0.0.0.0/0
            gateway: 10.64.0.1
        mtu: 9000
        dhcp: false
    nodeLabels: *workerLabels
  
  - hostname: verus
    ipAddress: 10.64.6.12
    controlPlane: false
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
      size: <= 150GB
    networkInterfaces:
      - interface: eno1
        addresses:
          - 10.64.6.12/20
        routes:
          - network: 0.0.0.0/0
            gateway: 10.64.0.1
        mtu: 9000
        dhcp: false
    nodeLabels: *workerLabels
  
  - hostname: mastema
    ipAddress: 10.64.6.13
    controlPlane: false
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
      size: <= 150GB
    networkInterfaces:
      - interface: eno1
        addresses:
          - 10.64.6.13/20
        routes:
          - network: 0.0.0.0/0
            gateway: 10.64.0.1
        mtu: 9000
        dhcp: false
    nodeLabels: *workerLabels
  
  - hostname: amdusias
    ipAddress: 10.64.6.14
    controlPlane: false
    disableSearchDomain: true
    installDiskSelector:
      type: nvme
      size: <= 150GB
    networkInterfaces:
      - interface: eno1
        addresses:
          - 10.64.6.14/20
        routes:
          - network: 0.0.0.0/0
            gateway: 10.64.0.1
        mtu: 9000
        dhcp: false
    nodeLabels: *workerLabels

controlPlane:
  inlinePatch:
    cluster:
      secretboxEncryptionSecret: ${secretboxEncryptionKey}
      apiServer:
        admissionControl: null
      # kube-proxy's job will be done better by Cilium
      proxy:
        disabled: true
    machine: &machine
      features:
        kubePrism:
          enabled: true
          port: 7445
      files:
        - content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
          path: /etc/cri/conf.d/20-customization.part
          op: create
      kubelet:
        extraArgs:
          feature-gates: GracefulNodeShutdown=true
          rotate-server-certificates: true
        nodeIP:
          validSubnets:
            - 10.64.6.0/24
      network:
        extraHostEntries:
          - aliases:
              - ${secretKubeDomainName}
            ip: ${clusterEndpointIP}
worker:
  inlinePatch:
    machine:
      <<: *machine
