clusterName: kclt-01
talosVersion: v1.1.2
kubernetesVersion: v1.24.4
endpoint: https://${clusterEndpointIP}:6443
#domain: cluster.local
clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/12
cniConfig:
  name: none
nodes:
  - hostname: formula #.${kubeDomainName}
    ipAddress: 10.64.8.1
    controlPlane: true
    installDisk: /dev/nvme0n1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        mtu: 1500
        vip:
          ip: ${clusterEndpointIP}
  - hostname: lailah #.${kubeDomainName}
    ipAddress: 10.64.8.3
    controlPlane: false
    installDisk: /dev/nvme0n1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        mtu: 1500
  - hostname: verus #.${kubeDomainName}
    ipAddress: 10.64.8.4
    controlPlane: false
    installDisk: /dev/nvme0n1
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
  - hostname: mastema #.${kubeDomainName}
    ipAddress: 10.64.8.5
    controlPlane: false
    installDisk: /dev/nvme0n1
    networkInterfaces:
      - interface: eth0
        mtu: 1500
        dhcp: true
controlPlane:
  inlinePatch:
    cluster:
      aescbcEncryptionSecret: ${aescbcEncryptionKey}
      aggregatorCA:
        crt: ${k8sAggregatorCert}
        key: ${k8sAggregatorCertKey}
      ca:
        crt: ${clusterCert}
        key: ${clusterCertKey}
      etcd:
        ca:
          crt: ${etcdCert}
          key: ${etcdCertKey}
      secret: ${clusterSecret}
      serviceAccount:
        key: ${k8sServiceAccountKey}
      apiServer:
        admissionControl: []
        certSANs:
          - ${secretPublicIp}
          - ${clusterEndpointIP}
          - ${kubeDomainName}
      token: ${clusterToken}
    machine:
      certSANs:
        - ${clusterEndpointIP}
        - ${secretPublicIp}
        - ${kubeDomainName}
      ca:
        crt: ${machineCert}
        key: ${machineCertKey}
      files:
        - content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
          path: /var/cri/conf.d/allow-unpriv-ports.toml
          op: create
      network:
        extraHostEntries:
          - aliases:
              - ${kubeDomainName}
            ip: ${clusterEndpointIP}
      token: ${machineToken}
worker:
  inlinePatch:
    cluster:
      aescbcEncryptionSecret: ${aescbcEncryptionKey}
      ca:
        crt: ${clusterCert}
        key: ${clusterCertKey}
      secret: ${clusterSecret}
      token: ${clusterToken}
    machine:
      ca:
        crt: ${machineCert}
        key: ${machineCertKey}
      certSANs:
        - ${secretPublicIp}
        - ${clusterEndpointIP}
        - ${kubeDomainName}
      files:
        - content: |
            [plugins."io.containerd.grpc.v1.cri"]
              enable_unprivileged_ports = true
              enable_unprivileged_icmp = true
          path: /var/cri/conf.d/allow-unpriv-ports.toml
          op: create
      network:
        extraHostEntries:
          - aliases:
              - ${kubeDomainName}
            ip: ${clusterEndpointIP}
      token: ${machineToken}
