---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 15m
  chart:
    spec:
      chart: kyverno
      version: 3.1.1
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    crds:
      install: true
    admissionController:
      replicas: 3
      serviceMonitor:
        enabled: true
      initContainer:
        extraArgs:
          - --autogenInternals=false
          - --clientRateLimitQPS=30
          - --clientRateLimitBurst=60
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: kyverno
