apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    cloudflare-token: ENC[AES256_GCM,data:4f0TEo/xLvVv0+zDER4e4CcBQ4KFKcgrgRWKzJYKCvtHWDm2MM31AA==,iv:o2Ll6AxRaajbrCAKa4WD0mURlYGtwP/r1QugY+YDpnw=,tag:vMyHCZlhvCqS3FSyFqZ34A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1spkux7hcrspxgl3xq8x7chykdr2d47q5l0jtucqu4gpkvre2cdfsgf38dz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWk5qSnJ0ODh6WkpyLzNx
            clhlVDBGRWUzdlhwc1YxVVBnVFhJdGlwcTEwCmJOUUxkcXNNQmxoN2c0S2pZbDZn
            bHB0VFZTZVdDcmxSVjFqQW96SlJvbjQKLS0tIDF5YnYxLzhiVnUrVXpUVG5wcGZ5
            eHdMMUZLeEt1eFlpNGduMlJYdXBwdjQKpQ4XHgtz/XqWErIahhvlM6cl16SOy7EQ
            TPQoXv8mDV5nd+IGeohwVsLWzfPEAEECD/5EGeODrPE1yenET7MLvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-22T21:09:54Z"
    mac: ENC[AES256_GCM,data:mfIeKdKVSaqCU/6ucIZGocjU14/CCjtEasQ35XODjKjSo2Y5v50E51o+nPqxHtdlXxPxZfFm6dJck7qMDFwIWOtTBWUuVkE6tNwsGheSmzZtATEAf0xwLH7qi7wb5FvYpWpLfJSI17N5M9b44s5WGJG3CfrK90BMh/TbHKx3gTA=,iv:31P9YmtjeKU35CXVprF2aU7dUHY2Hf7t46X5QxjBlIw=,tag:GQKcri0c35ysj0raDmcijQ==,type:str]
    pgp:
        - created_at: "2022-07-22T21:09:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hF4DaZXJ7CKj2AMSAQdA+J5iBIA+MLxngCUmTWnfeiJqC1IwtwYroFEH1WMujhQw
            nF585rNuwKaIj+aZgLnUuTgzS/A5AzK/rmWyf56xjmsJLJG2dV/juyR0v9Z2WqeH
            0lwBtzW1pvLi7d1K8Sr2bLFvZfP+QmUM2hkKvPpZJsFrukyRTts0LwawL6T9rxiZ
            8uIRE35KEgS0P5jIsnmmCN/ehvmkHbU5mUyEHHnQkTgf0TTyDKta2yfw9xuB0g==
            =mhcP
            -----END PGP MESSAGE-----
          fp: 2CE2F0FA3F3E807815447A06B5B5EEA464CA97AB
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.3
