---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 6.59.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    replicas: 3
    env:
      GF_EXPLORE_ENABLED: true
      GF_PANELS_DISABLE_SANITIZE_HTML: true
      GF_LOG_FILTERS: rendering:debug
      GF_DATE_FORMATS_FULL_DATE: "YYYY-MM-DD HH:mm:ss.SSSSZZ"
      GF_DATE_FORMATS_INTERVAL_SECOND: "HH:mm:ss.SSSS"
      GF_DATE_FORMATS_INTERVAL_MINUTE: "HH:mm:ss"
      GF_DATE_FORMATS_INTERVAL_HOUR: "DD/MM HH:mm (ZZ)"
      GF_DATE_FORMATS_INTERVAL_DAY: "DD MMM"
      GF_DATE_FORMATS_INTERVAL_MONTH: "MMM YYYY"
      GF_DATE_FORMATS_INTERVAL_YEAR: "Y"
      GF_DATE_FORMATS_DEFAULT_TIME_ZONE: "${TZ}"
      GF_SECURITY_ALLOW_EMBEDDING: true
      GF_SECURITY_COOKIE_SAMESITE: grafana
      DS_PROMETHEUS: Prometheus
    admin:
      existingSecret: grafana-admin-creds
    grafana.ini:
      server:
        root_url: "https://grafana.${CLUSTER_NAME}.sys.${GLOBALSECRET__PUBLIC_DOMAIN}"
      paths:
        data: /var/lib/grafana/data
        logs: /var/log/grafana
        plugins: /var/lib/grafana/plugins
        provisioning: /etc/grafana/provisioning
      analytics:
        check_for_updates: false
      log:
        mode: console
      grafana_net:
        url: https://grafana.net
      auth:
        signout_redirect_url: "https://auth.${GLOBALSECRET__PUBLIC_DOMAIN}/logout"
        oauth_auto_login: true
      auth.basic:
        disable_login_form: false
      auth.generic_oauth:
        enabled: true
      dashboardProviders:

