---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-grafana
  namespace: flux-system
spec:
  path: ${CLUSTER_PATH}/apps/monitoring/grafana/app
  dependsOn:
    - name: cluster-apps-grafana-cnpg-cluster
    - name: cluster-apps-cert-manager-issuers
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-grafana-cnpg-cluster
  namespace: flux-system
spec:
  path: ${CLUSTER_PATH}/apps/monitoring/grafana/cnpg-cluster
  dependsOn:
    - name: cluster-apps-cloudnative-pg
    - name: cluster-apps-rook-ceph-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
