---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cilium
  namespace: flux-system
spec:
  path: ${CLUSTER_PATH}/apps/kube-system/cilium/app
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: ops
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-cilium-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cilium
  path: ${CLUSTER_PATH}/apps/kube-system/cilium/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: ops
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
