---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: grafana-cnpg
  namespace: monitoring
spec:
  schedule: "@daily"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: grafana-cnpg
