---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup.yaml
  - cluster.yaml
  - grafana-cnpg-user-grafana.sops.yaml
  - grafana-cnpg-user-superuser.sops.yaml
  - objectbucketclaim.yaml
