apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "watch-${SECRET_TERTIARY_DOMAIN/./-}"
  namespace: default
spec:
  secretName: &host "watch.${SECRET_TERTIARY_DOMAIN}"
  issuerRef:
    name: "${CERT_DEFAULT_CLUSTERISSUER}"
    kind: ClusterIssuer
  commonName: *host 
  dnsNames:
  - *host 
