---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    env:
      DB_HOSTNAME: "immich-cnpg-rw.default.svc.cluster.local"
      DB_PORT: "5432"
      DB_DATABASE_NAME: "immich"
      REDIS_HOSTNAME: "immich-redis.default.svc.cluster.local"
      TYPESENSE_HOST: "immich-typesense.default.svc.cluster.local"
      IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning.svc.cluster.local:3003"


    image:
      tag: v1.89.0


    immich:
      persistence:
        library:
          existingClaim: immich-media

    
    machine-learning:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-machine-learning
        tag: v1.90.2@sha256:db29ac9e6c1205912df176b81c5c605a98ee18220e438b17151e84c5c5becfa1
        pullPolicy: IfNotPresent
      
      env:
        TRANSFORMERS_CACHE: /cache
      
      persistence:
        cache:
          enabled: true
          size: 16Gi
          type: pvc
          accessMode: ReadWriteMany
          storageClass: ${CLUSTER_STORAGE_FILESYSTEM_SSD}


    microservices:
      enabled: true
      env:
        REVERSE_GEOCODING_DUMP_DIRECTORY: /geodata-cache
      
      persistence:
        geodata-cache:
          enabled: true
          size: 1Gi
          type: pvc
          accessMode: ReadWriteMany
          storageClass: ${CLUSTER_STORAGE_FILESYSTEM_SSD}
        image: &serverImage
          repository: ghcr.io/immich-app/immich-server
          tag: v1.90.2@sha256:3e68be128c705f4e1c565a38f0a70c7008504f0acaaf122dc13cc6716a69a067
          pullPolicy: IfNotPresent


    server:
      enabled: true
      image: *serverImage

      ingress:
        main:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hosts:
            - host: &host immich.${GLOBALSECRET__PUBLIC_DOMAIN}
              paths:
                - path: "/"
                  type: Prefix
          tls:
            - hosts:
                - *host
              secretName: *host


    typesense:
      enabled: true
      env:
        TYPESENSE_DATA_DIR: /tsdata
      
      image:
        repository: typesense/typesense
        tag: 0.25.1@sha256:035ccfbc3fd8fb9085ea205fdcb62de63eaefdbebd710e88e57f978a30f2090d
        pullPolicy: IfNotPresent
      
      persistence:
        tsdata:
          enabled: true
          accessMode: ReadWriteOnce
          size: 2Gi
          storageClass: ${CLUSTER_STORAGE_BLOCK_SSD}
  valuesFrom:
    - targetPath: env.DB_USERNAME
      kind: Secret
      name: immich-cnpg-user-superuser
      valuesKey: username
    - targetPath: env.DB_PASSWORD
      kind: Secret
      name: immich-cnpg-user-superuser
      valuesKey: password
    - targetPath: typesense.env.TYPESENSE_API_KEY
      kind: Secret
      name: immich-typesense-api-key
      valuesKey: key
