apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET__PARTNER_DOMAIN/./-}"
  namespace: networking
spec:
  secretName: "${SECRET__PARTNER_DOMAIN}"
  issuerRef:
    name: "${CERT_DEFAULT_CLUSTERISSUER}"
    kind: ClusterIssuer
  commonName: "${SECRET__PARTNER_DOMAIN}"
  dnsNames:
  - "${SECRET__PARTNER_DOMAIN}"
  - "*.${SECRET__PARTNER_DOMAIN}"
