apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${GLOBALSECRET__PUBLIC_DOMAIN/./-}"
  namespace: networking 
spec:
  secretName: "${GLOBALSECRET__PUBLIC_DOMAIN}"
  issuerRef:
    name: "${CERT_DEFAULT_CLUSTERISSUER}"
    kind: ClusterIssuer
    # No namespace is set as ClusterIssuers are cluster-scope.
    # ns is only set at all as CI's ref a secret.
  commonName: "${GLOBALSECRET__PUBLIC_DOMAIN}"
  dnsNames:
  - "${GLOBALSECRET__PUBLIC_DOMAIN}"
  - "*.git.${GLOBALSECRET__PUBLIC_DOMAIN}"
  - "*.sys.${GLOBALSECRET__PUBLIC_DOMAIN}"
  - "*.${GLOBALSECRET__PUBLIC_DOMAIN}"
