apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${GLOBALSECRET__SHORT_DOMAIN/./-}"
  namespace: networking 
spec:
  secretName: "${GLOBALSECRET__SHORT_DOMAIN}"
  issuerRef:
    name: "${CERT_DEFAULT_CLUSTERISSUER}"
    kind: ClusterIssuer
  commonName: "${GLOBALSECRET__SHORT_DOMAIN}"
  dnsNames:
  - "${GLOBALSECRET__SHORT_DOMAIN}"
  - "*.${GLOBALSECRET__SHORT_DOMAIN}"
