apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET__TERTIARY_DOMAIN/./-}"
  namespace: networking 
spec:
  secretName: "${SECRET__TERTIARY_DOMAIN}"
  issuerRef:
    name: "${CERT_DEFAULT_CLUSTERISSUER}"
    kind: ClusterIssuer
  commonName: "${SECRET__TERTIARY_DOMAIN}"
  dnsNames:
  - "${SECRET__TERTIARY_DOMAIN}"
  - "*.${SECRET__TERTIARY_DOMAIN}"
