apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${GLOBALSECRET__TESTING_DOMAIN/./-}"
  namespace: networking 
spec:
  secretName: "${GLOBALSECRET__TESTING_DOMAIN}"
  issuerRef:
    name: "${CERT_DEFAULT_CLUSTERISSUER}"
    kind: ClusterIssuer
  commonName: "${GLOBALSECRET__TESTING_DOMAIN}"
  dnsNames:
  - "${GLOBALSECRET__TESTING_DOMAIN}"
  - "*.${GLOBALSECRET__TESTING_DOMAIN}"
  - "*.git.${GLOBALSECRET__TESTING_DOMAIN}"
  - "*.sys.${GLOBALSECRET__TESTING_DOMAIN}"
