---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: auth
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2023.3.0
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
      interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cloudnative-pg
      namespace: database
      # uses built-in redis for the time being.
    #- name: redis-cluster
    #  namespace: auth
  values:
    authentik:
      error_reporting:
        enabled: true
      postgresql:
        # Uses a dedicated cnpg cluster.
        host: "authentik-cnpg-rw"
        name: "authentik"
    postgresql:
      # disable the built-in PostgreSQL chart.
      enabled: false
    prometheus:
      rules:
        create: true
      serviceMonitor:
        create: true
    ingress:
      ingressClassName: "nginx"
      enabled: true
      hosts:
        - host: &host auth.${GLOBALSECRET__PUBLIC_DOMAIN}
          paths:
            - path: "/"
              pathType: Prefix
    redis:
      # enable the built-in redis chart.
      # TODO: Move away from redis built-in subchart.
      enabled: true
    replicas: 3
    securityContext:
      fsGroup: 1000
    volumes:
      - name: media
        persistentVolumeClaim:
          claimName: authentik-media
    volumeMounts:
      - name: media
        mountPath: /media
    worker:
      replicas: 3
      securityContext:
        fsGroup: 1000
  valuesFrom:
    - targetPath: authentik.secret_key
      kind: Secret
      name: authentik-config-secrets
      valuesKey: AUTHENTIK_SECRET_KEY
    - targetPath: authentik.postgresql.password
      kind: Secret
      # the authentik user generated by CNPG initdb
      name: authentik-cnpg-superuser
      valuesKey: password
    - targetPath: authentik.postgresql.user
      kind: Secret
      # the authentik user generated by CNPG initdb
      name: authentik-cnpg-superuser
      valuesKey: username
