---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: grafana
      version: 6.61.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 30m
  maxHistory: 3
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            disableDeletion: false
            editable: true
            folder: ""
            options:
              path: /var/lib/grafana/dashboards/default
            orgId: 1
            type: file
          - name: node-exporter
            disableDeletion: false
            editable: true
            folder: "node-exporter"
            options:
              path: /var/lib/grafana/dashboards/node-exporter
            orgId: 1
            type: file
          - name: unpoller
            disableDeletion: false
            editable: true
            folder: "UniFi Poller"
            options:
              path: /var/lib/grafana/dashboards/unpoller
            orgId: 1
            type: file
    

    dashboards:
      default:
      
      rook-ceph:
        # Ref: https://grafana.com/grafana/dashboards/2842-ceph-cluster/
        ceph-cluster:
          gnetId: 2842
          revision: 17
          datasource: {}


    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - access: proxy
            isDefault: true
            name: Prometheus
            type: prometheus
    deploymentStrategy:
      type: Recreate
    

    grafana.ini:
      auth:
        signout_redirect_url: "https://auth.${GLOBALSECRET__PUBLIC_DOMAIN}/o/grafana/end-session/"
        oauth_auto_login: true
      
      auth.generic_oauth:
        name: "Auth@Dotfile"
        enabled: true
        scopes: "openid profile email"
        auth_url: "https://auth.${GLOBALSECRET__PUBLIC_DOMAIN}/application/o/authorize/"
        token_url: "https://auth.${GLOBALSECRET__PUBLIC_DOMAIN}/application/o/token/"
        api_url: "https://auth.${GLOBALSECRET__PUBLIC_DOMAIN}/application/o/userinfo"
      
      server:
        domain: &host grafana.global.sys.${GLOBALSECRET__PUBLIC_DOMAIN}
        root_url: "%(protocol)s://%(domain)s/"
    

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      
      hosts:
        - *host
      
      tls:
        - hosts:
          - *host
    

    plugins:
    - grafana-clock-panel
    - natel-discrete-panel
    - pr0ps-trackmap-panel
    

    rbac:
      pspEnabled: false
    

    serviceAccount:
      autoMount: true
    

    serviceMonitor:
      enabled: true
  valuesFrom:
    - targetPath: env.GF_AUTH_GENERIC_OAUTH_CLIENT_ID
      kind: Secret
      name: grafana-secrets
      valuesKey: authentik-client_id
    - targetPath: env.GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET 
      kind: Secret
      name: grafana-secrets
      valuesKey: authentik-client_secret
    - targetPath: env.GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH
      kind: Secret
      name: grafana-secrets
      valuesKey: authentik-roles
