---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cilium
    app.kubernetes.io/instance: cilium
spec:
  loadBalancerIPs: true
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  serviceSelector:
    matchLabels:
      io.cilium/lb-ipam-layer2: "true"
