---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: source-cloudnative-pg
  namespace: flux-system
spec:
  interval: 6h
  url: https://github.com/cloudnative-pg/charts.git
  ref:
    # renovate: registryUrl=https://cloudnative-pg.github.io/charts chart=cloudnative-pg
    tag: cloudnative-pg-0.17.0
  ignore: |
    # exclude all
    /*
    # include crd directory
    !/charts/cloudnative-pg/templates/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: crds-cloudnative-pg
  namespace: flux-system
spec:
  interval: 6h
  prune: false
  timeout: 5m0s
  wait: true
  sourceRef:
    kind: GitRepository
    name: source-cloudnative-pg
    namespace: flux-system
