---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-configs
data:
  CLUSTER_NAME: "kclt-01"

  TIMEZONE: "America/New_York"
  # cert-manager
  CERT_DEFAULT_CLUSTERISSUER: "letsencrypt-production"
  CERT_STAGING_CLUSTERISSUER: "letsencrypt-staging"
  CERT_PRODUCTION_CLUSTERISSUER: "letsencrypt-production"
  
  # cilium
  CILIUM_LB_CIDR: "10.64.3.0/24"
  CILIUM_LB_INGRESS_ADDR: "10.64.3.1"
  CILIUM_LB_MINECRAFTSURVIVAL_ADDR: "10.64.3.2"

  # storage
  CLUSTER_STORAGE_BLOCK: "ceph-block"
  CLUSTER_STORAGE_FILESYSTEM: "ceph-filesystem"
  CLUSTER_STORAGE_BUCKET: "ceph-bucket"
  
